### ISSUE TITLE
updt link to signup

### ISSUE THREAD

**Issue by marracci** [blegeer/ENVIDGMapsAPI#1]
Hi @blegeer - can you please update the signup link for DigitalGlobe Maps API?
should be:

https://platform.digitalglobe.com/maps-api

FYI - We've posted the integration details here on our DG Maps API [docs site](https://mapsapidocs.digitalglobe.com/docs/maps-api-envi).

Cheers!

**Comment by blegeer** [comment]
Updated link in the README file to the current
